name: Linux_CI
on:
  # push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Onnxruntime-TVM:
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    steps:
       - uses: actions/checkout@v4
         with:
           submodules: true
       - uses: deadsnakes/action@v2.1.1
         with:
           python-version: '3.11'
       - name: 'Setup TVM EP requirements'
         run: |
           set -e -x
           sudo apt-get update
           sudo apt-get install -y libtinfo-dev zlib1g-dev build-essential libedit-dev libxml2-dev nasm
           python3 -m pip install -r ${{ github.workspace }}/tools/ci_build/github/linux/tvm/requirements.txt
       - name: 'Build and Test'
         run: |
           python3 ${{ github.workspace }}/tools/ci_build/build.py --build_dir build --config Release --skip_submodule_sync --parallel --enable_pybind --build_wheel --skip_tests --skip_onnx_tests --use_tvm
       - uses: actions/upload-artifact@v3
         with:
           name: wheels
           path: |
             build/Release/dist/*.whl
             build/Release/_deps/tvm-src/python/dist/*.whl
